import {BrowserRouter} from 'react-router-dom'
import {Routes}; {Route}, {Navigate} from 'react-router-dom'
import {AuthProvider} from './context/AuthContext'
import {ProtectedRoute} from './utils/ProtectedRoute'
import './App.css'
